[project]
name = "channel-point-discord"
version = "0.1.0"
description = "like a twitch channel point system in discord"
readme = "README.md"
requires-python = ">=3.6"
dependencies = [
    "psycopg2-binary>=2.9.8",
    "sqlalchemy>=1.4.54",
]
